import json
import logging
from datetime import datetime, timezone

from fastapi import APIRouter, HTTPException, Request

logger = logging.getLogger(__name__)

from config import EXPORTS_DIR
from database import get_meeting, update_ai_output, update_verified_output, record_export
from llm_client import analyze_transcript, get_available_providers

router = APIRouter(prefix="/api", tags=["analyze"])


@router.get("/providers")
def providers():
    available = get_available_providers()
    return {"providers": available, "default": available[0] if available else None}


@router.post("/analyze")
async def analyze(request: Request):
    body = await request.json()
    meeting_id = body.get("meeting_id")
    provider = body.get("provider")
    if not meeting_id:
        raise HTTPException(status_code=400, detail="meeting_id is required")

    meeting = get_meeting(meeting_id)
    if not meeting:
        raise HTTPException(status_code=404, detail="Meeting not found")

    utterances = meeting["utterances_json"]
    if not utterances:
        raise HTTPException(status_code=400, detail="No utterances found for this meeting")

    try:
        ai_output = analyze_transcript(utterances, provider=provider)
    except PermissionError as e:
        raise HTTPException(status_code=401, detail=str(e))
    except ConnectionError as e:
        raise HTTPException(status_code=429, detail=str(e))
    except RuntimeError as e:
        raise HTTPException(status_code=502, detail=str(e))
    except ValueError as e:
        raise HTTPException(status_code=422, detail=str(e))
    except Exception as e:
        # Catch provider-specific exceptions
        err_name = type(e).__name__
        if "AuthenticationError" in err_name:
            raise HTTPException(status_code=401, detail=f"Invalid API key: {e}")
        if "RateLimitError" in err_name:
            raise HTTPException(status_code=429, detail=f"Rate limited. Please wait and retry: {e}")
        raise HTTPException(status_code=502, detail=f"LLM API error: {e}")

    update_ai_output(meeting_id, ai_output)

    return {"meeting_id": meeting_id, "status": "analyzed", "ai_output": ai_output}


def _generate_markdown(meeting: dict, verified: dict) -> str:
    md = []
    meta = verified.get("meeting_metadata", {})
    md.append(f"# {meta.get('title', meeting['title'])}")
    md.append(f"\n**Date:** {meta.get('date_mentioned', 'Not specified')}")
    md.append(f"**Participants:** {', '.join(meta.get('participants', []))}")
    md.append(f"**Status:** Approved")
    md.append(f"**Exported:** {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}")

    if verified.get("state_of_direction"):
        md.append(f"\n## State of Direction\n\n{verified['state_of_direction']}")

    if verified.get("decisions"):
        md.append("\n## Decisions\n")
        md.append("| ID | Decision | Made By | Confidence |")
        md.append("|-----|----------|---------|------------|")
        for d in verified["decisions"]:
            md.append(f"| {d['id']} | {d['description']} | {d.get('made_by', 'N/A')} | {d.get('confidence', 'N/A')} |")
            if d.get("source_quote"):
                md.append(f"\n> {d['source_quote']}\n")

    if verified.get("action_items"):
        md.append("\n## Action Items\n")
        md.append("| ID | Task | Owner | Deadline | Confidence |")
        md.append("|-----|------|-------|----------|------------|")
        for a in verified["action_items"]:
            md.append(f"| {a['id']} | {a['task']} | {a.get('owner', 'Unassigned')} | {a.get('deadline', 'N/A')} | {a.get('confidence', 'N/A')} |")
            if a.get("source_quote"):
                md.append(f"\n> {a['source_quote']}\n")

    if verified.get("open_risks"):
        md.append("\n## Open Risks\n")
        md.append("| ID | Risk | Raised By | Severity |")
        md.append("|-----|------|-----------|----------|")
        for r in verified["open_risks"]:
            md.append(f"| {r['id']} | {r['description']} | {r.get('raised_by', 'N/A')} | {r.get('severity', 'N/A')} |")
            if r.get("source_quote"):
                md.append(f"\n> {r['source_quote']}\n")

    if verified.get("trust_flags"):
        md.append("\n## Trust Flags\n")
        for flag in verified["trust_flags"]:
            md.append(f"- {flag}")

    md.append("\n---\n*Generated by Brainstorm Boost*\n")
    return "\n".join(md)


@router.post("/approve")
async def approve(request: Request):
    body = await request.json()
    meeting_id = body.get("meeting_id")
    verified_output = body.get("verified_output")

    if not meeting_id or not verified_output:
        raise HTTPException(status_code=400, detail="meeting_id and verified_output are required")

    meeting = get_meeting(meeting_id)
    if not meeting:
        raise HTTPException(status_code=404, detail="Meeting not found")

    update_verified_output(meeting_id, verified_output)

    # Auto-index into meeting memory for RAG queries
    try:
        from routes.query import get_memory
        memory = get_memory()
        memory.index_meeting(meeting_id, verified_output)
    except Exception:
        logger.exception("Failed to auto-index meeting %s into memory", meeting_id)

    # Extract action items into dedicated table
    try:
        from database import create_action_item, upsert_speaker_profile
        for a in verified_output.get("action_items", []):
            create_action_item(
                meeting_id=meeting_id,
                task=a.get("task", ""),
                owner=a.get("owner"),
                deadline=a.get("deadline"),
                confidence=a.get("confidence"),
                source_quote=a.get("source_quote"),
            )
        participants = verified_output.get("meeting_metadata", {}).get("participants", [])
        for name in participants:
            title = verified_output.get("meeting_metadata", {}).get("title", "")
            upsert_speaker_profile(name=name, topics=[title] if title else [], meeting_count=1)
    except Exception:
        logger.exception("Failed to extract action items for meeting %s", meeting_id)

    # Generate exports
    safe_title = "".join(c if c.isalnum() or c in "-_ " else "" for c in meeting["title"])[:50].strip()
    ts = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
    base_name = f"{safe_title}_{ts}".replace(" ", "_")

    # Markdown export
    md_filename = f"{base_name}.md"
    md_path = EXPORTS_DIR / md_filename
    md_content = _generate_markdown(meeting, verified_output)
    md_path.write_text(md_content)
    record_export(meeting_id, md_filename, "markdown")

    # JSON export
    json_filename = f"{base_name}.json"
    json_path = EXPORTS_DIR / json_filename
    json_path.write_text(json.dumps(verified_output, indent=2))
    record_export(meeting_id, json_filename, "json")

    return {
        "meeting_id": meeting_id,
        "status": "approved",
        "exports": {
            "markdown": f"/exports/{md_filename}",
            "json": f"/exports/{json_filename}",
        },
    }
